### ISSUE TITLE
Script Language Registry

### ISSUE THREAD

**Issue by diamonddevv** [diamonddevv/luafy#25]
Add registry for Script Languages. This will allow other mods to add more Language support.

**Comment by MulverineX** [comment]
This is probably how Bun support would be implemented, where `.ts` & `.bun.bin` (JavascriptCore bytecode, depends on https://github.com/oven-sh/bun/issues/6798 ) files would be targetted by an addon mod.

**Comment by diamonddevv** [comment]
completed!
