### ISSUE TITLE
Add support for directly applying a static resource `png` to a text display's component field

### ISSUE THREAD

**Issue by MulverineX** [diamonddevv/luafy#32]
~~PNG Decoding: https://github.com/leonbloy/pngj ~~ (superseded by Java's `BufferedImage`)

Prior Art: https://github.com/AjaxGb/mc-text-image/blob/master/text-image.js

For performance reasons this doesn't return the text component and is something you directly apply to a text display's `EntityScriptObject`.

Should support client-side text displays from #7

**Comment by diamonddevv** [comment]
complete, par #7 integration
