### ISSUE TITLE
1.21

### ISSUE THREAD

**Issue by diamonddevv** [diamonddevv/luafy#36]
Update mod to 1.21. This includes updating necessary APIs to use newer features (Item Components <- NBT)

**Comment by diamonddevv** [comment]
donezoo :) this was done a while ago, i just forgot to close the issue.
components are a little buggy

**Comment by Jipok** [comment]
@diamonddevv
Can you post the build on modrinch or somewhere else?
I tried to build it myself for 1.21.1 but it didn't work.

**Comment by diamonddevv** [comment]
@Jipok i will! unfortunately, i think its a little buggy and unstable right now and the mod isn't high on my list of priorities.
