### ISSUE TITLE
Add `set_motion` method to entities

### ISSUE THREAD

**Issue by MulverineX** [diamonddevv/luafy#5]
```mcfunction
motion <targets> (set|add) value <x> <y> <z>
motion <targets> (set|add) from entity <target> [path] [scale]
motion <targets> (set|add) from storage <target> [path] [scale]
motion <targets> (set|add) from block <x> <y> <z> <path> [scale]
motion <targets> magnitude (set|add) from ...
...
motion <targets> magnitude (set|add|multiply) value <value>
motion <targets> toward block <x> <y> <z> (add|set) none <strength>
motion <targets> toward block <x> <y> <z> (add|set) <scaling> <nearStrength> <farStrength> <nearRadius> <farRadius>
motion <targets> toward entity <targets> add ...
motion <targets> toward entity <target> set ...
...
data modify ... set motion <target> (vector|magnitude|rotation)
data modify ... set motion <player> input (vector|magnitude|rotation)
```
- `from` will either accept a `[float, float, float]` or a `float`, and when applicable, defaults to the `Motion` key
- motion applied to players is simply an *influence* similar to tnt explosions & knockback. We are not asking for arcane changes to the server-client protocol, it is understood that additional handling (ie. `tp` corrections) is occasionally needed

(specific mechanics are defined [here](<https://gist.github.com/AjaxGb/ad6119caa317a640b24d70c332d3ff91>), credit @ajaxgb)

This command is effectively what the datapack community needs to establish effective control over entity motion, so a parallel to this in Luafy would be excellent.

**Comment by diamonddevv** [comment]
partially complete ; set/add/multiply methods exist.

will continue to create a "towards block" version

**Comment by diamonddevv** [comment]
done!
